// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdpQeosgk0jLQcrtgF3H0yS61AAVYk_KA',
    appId: '1:266939016833:web:bc45bd985cc2eafd5b8f80',
    messagingSenderId: '266939016833',
    projectId: 'mynotespublish',
    authDomain: 'mynotespublish.firebaseapp.com',
    storageBucket: 'mynotespublish.appspot.com',
    measurementId: 'G-8ZDPMH3DYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzTm5n8wVjlEkZTBYfHSg8CbRP9UdDtak',
    appId: '1:266939016833:android:c017840f16a66dc85b8f80',
    messagingSenderId: '266939016833',
    projectId: 'mynotespublish',
    storageBucket: 'mynotespublish.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmXdtj3pO1lzG4q12n6A8f1O4Tk2KHyRM',
    appId: '1:266939016833:ios:84e091b7fedc55525b8f80',
    messagingSenderId: '266939016833',
    projectId: 'mynotespublish',
    storageBucket: 'mynotespublish.appspot.com',
    iosBundleId: 'com.example.mynotespublish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmXdtj3pO1lzG4q12n6A8f1O4Tk2KHyRM',
    appId: '1:266939016833:ios:f8aa3acee1bffd115b8f80',
    messagingSenderId: '266939016833',
    projectId: 'mynotespublish',
    storageBucket: 'mynotespublish.appspot.com',
    iosBundleId: 'com.example.mynotespublish.RunnerTests',
  );
}
